### ISSUE TITLE
Support Artix

### ISSUE THREAD

**Issue by TornaxO7** [MenkeTechnologies/zpwr#11]
**Is your feature request related to a problem? Please describe.**
I'm getting the following error if I'm running the insaller:

```
////////////////////////////////////////////////////////////////////////////////
/////////////  5>>> Your ZPWR_DISTRO_FAMILY artix is unsupported!  /////////////
////////////////////////////////////////////////////////////////////////////////
```

**Describe the solution you'd like**
Well, that artix gets supported :D

**Describe alternatives you've considered**
*pika!*

**Comment by MenkeTechnologies** [comment]
supported now

https://github.com/MenkeTechnologies/zpwr/commit/312bc60b3a8f759abbeeb0a6e7905fa6e016b7cd

**Comment by TornaxO7** [comment]
thanks!
