### ISSUE TITLE
Arco

### ISSUE THREAD

**Issue by fkf6116** [MenkeTechnologies/zpwr#14]
**I can't install it on arco**
Arco linux is almost the same as arch or garuda but it's unfortunately not supported 
please add it

**Comment by MenkeTechnologies** [comment]
what is the contents of `/etc/os-release`?

**Comment by MenkeTechnologies** [comment]
nvm, just added support.  dont have a VM right now to test tho

**Comment by MenkeTechnologies** [comment]
I installed on Arco Linux VM with no issues
