### ISSUE TITLE
Combine all packages in one install

### ISSUE THREAD

**Issue by signed-log** [MenkeTechnologies/zpwr#2]
**Is your feature request related to a problem? Please describe.**
I don't understand why there is the need to install each packages in it's own command
**Describe the solution you'd like**
Combine ever package installation in a single command, letting package manager figure out if the package is already installed

**Comment by MenkeTechnologies** [comment]
Hi, there is no need to have separate package manager install commands but I like to see the banner which displays the currently installing package
