### ISSUE TITLE
Unable to connect to a repository at URL

### ISSUE THREAD

**Issue by redbeardymcgee** [MenkeTechnologies/zpwr#20]
**Describe the bug**
```
Setting up snippet: OMZP::yum
Downloading `OMZP::yum` (with Subversion)…
svn: E170013: Unable to connect to a repository at URL 'https://github.com/ohmyzsh/ohmyzsh/trunk/plugins/yum'
svn: E160013: '/ohmyzsh/ohmyzsh/trunk/plugins/yum' path not found

Setting up snippet: OMZP::dnf
Downloading `OMZP::dnf` (with Subversion)…
svn: E170013: Unable to connect to a repository at URL 'https://github.com/ohmyzsh/ohmyzsh/trunk/plugins/dnf'
svn: E160013: '/ohmyzsh/ohmyzsh/trunk/plugins/dnf' path not found
/home/josh/.zpwr/local/.tokens-post.sh: line 30: (r)_mise_hook: syntax error in expression (error token is "_mise_hook")
/home/josh/.zpwr/local/.tokens-post.sh: line 30: (r)_mise_hook: syntax error in expression (error token is "_mise_hook")
/home/josh/.zpwr/local/.tokens-post.sh: line 30: (r)_mise_hook: syntax error in expression (error token is "_mise_hook")
/home/josh/.zpwr/local/.tokens-post.sh: line 30: (r)_mise_hook: syntax error in expression (error token is "_mise_hook")
/home/josh/.zpwr/local/.tokens-post.sh: line 30: (r)_mise_hook: syntax error in expression (error token is "_mise_hook")
/home/josh/.zpwr/local/.tokens-post.sh: line 30: (r)_mise_hook: syntax error in expression (error token is "_mise_hook")
/home/josh/.zpwr/local/.tokens-post.sh: line 30: (r)_mise_hook: syntax error in expression (error token is "_mise_hook")
/home/josh/.zpwr/local/.tokens-post.sh: line 30: (r)_mise_hook: syntax error in expression (error token is "_mise_hook")
```

**To Reproduce**
`zpwr` and `mise` are installed as normal in the host system.

1. `distrobox create --yes --image registry.fedoraproject.org/fedora-toolbox:35 --name fedora-toolbox ---additional-packages zsh`
2. `eval "$(mise activate zsh)"` in `"$ZPWR/.local/.tokens-post.sh"` (same problem with `.tokens.sh`)
3. `distrobox enter --name fedora-toolbox -- zsh -l`

**Expected behavior**
Presumably these plugins should just install themselves with no error, and the `mise` activation shouldn't error either. At least, it should maybe error only once, not 8 times.

**Additional context**
My host system had no problem with zpwr, but i'm testing a dev env in a distrobox. By dev env, i just mean my Emacs and language tools.

I also have every expectation that i've just fumbled something myself, so if i've done an ignorant thing somewhere, feel free to let me know plainly.

Alternatively, this might not be zpwr's fault. Maybe it's a distrobox quirk that you can't foresee. That's okay too, i'll be fine without zsh in my emacs if I can't have it.

**Desktop (please complete the following information):**
pop os 22.04 LTS

**Comment by MenkeTechnologies** [comment]
Caused by

https://github.blog/2023-01-20-sunsetting-subversion-support/

GitHub removed subversion support on Monday.  Zinit uses subversion to install OMZ plugins as snippets.

I added a new commit that reworks the snippet loading without using subversion.

Any issue with eval of `mise activate zsh` is outside of my control.

**Comment by MenkeTechnologies** [comment]
I am not able to handle the macos OMZ plugin due to additional files needing to be downloaded.

https://github.com/zdharma-continuum/zinit/issues/504
