### ISSUE TITLE
terminal freeze when setting up ZPWR_GITHUB_ACCOUNT

### ISSUE THREAD

**Issue by segmentationf4u1t** [MenkeTechnologies/zpwr#4]
**Describe the bug**
After setting up the env variable to anything it does freeze terminal upon entering zsh

**To Reproduce**
Set up enviornmental variable of ZPWR_GITHUB_ACCOUNT in ~/.zpwr/local/.tokens.sh

**Expected behavior**
Self explanatory.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Version [e.g. 22] 20.04 LTS

**Comment by MenkeTechnologies** [comment]
From the Readme


> With Zinit Turbo mode, despite the number of plugins and completions, startup usually takes < 1 second on faster machines but up to 2-10 seconds on slow machines such as WSL. Zinit runs compinit in the background after startup and you will experience a brief lockup (unnoticeable if zpwr regenzsh and zpwr recompile have run to create .zcompdump.zwc). This variable controls the delay between prompt and compinit.
> 
> export ZPWR_ZINIT_COMPINIT_DELAY=0


so wait then run zpwr regenzsh and zpwr recompile.  or zpwr regen for all caches.
