### ISSUE TITLE
Changing zinit Repository

### ISSUE THREAD

**Issue by RaZ0rr-Two** [MenkeTechnologies/zpwr#5]
Please see the post below to adapt the necessary changes :+1: 

https://www.reddit.com/r/zsh/comments/qinb6j/httpsgithubcomzdharma_has_suddenly_disappeared_i/

**Comment by MenkeTechnologies** [comment]
https://github.com/MenkeTechnologies/zpwr/commit/343fbfe74df872f1bc28bbcdd04ffbe1c5911694
