### ISSUE TITLE
Zdharma has been deleted from Github

### ISSUE THREAD

**Issue by luong-komorebi** [MenkeTechnologies/zpwr#6]
More context over here https://github.com/zdharma-continuum/I_WANT_TO_HELP 

Could you check your local machine for possible copy of zsh-unique-id? This repo has 0 fork so it is really hard to find a copy of it and repost on @zdharma-continuum

**Comment by MenkeTechnologies** [comment]
unfortunate situation...

https://github.com/MenkeTechnologies/zpwr/commit/343fbfe74df872f1bc28bbcdd04ffbe1c5911694

**Comment by lmburns** [comment]
> More context over here https://github.com/zdharma-continuum/I_WANT_TO_HELP
> 
> Could you check your local machine for possible copy of zsh-unique-id? This repo has 0 fork so it is really hard to find a copy of it and repost on @zdharma-continuum

I have a copy of it. I have the following from `zdharma`:
* `declare-zsh`
* `fast-syntax-highlighting`
* `history-search-multi-word`
* `zbrowse`
* `zconvey`
* `zflai`
* `zinit`
* `zinit-crasis`
* `zsh-startify`
* `zsh-unique-id`
* `zshelldoc`
* `zui`

I have the following from `psprint`:
* `zsh-cmd-architect`
* `zsh-editing-workbench`
* `zsh-navigation-tools`
* `zsh-select`

I started my own mirror of this as well with the user `@zdharma-zmirror` and haven't uploaded all of my copies but am going to. I can send these to you if you would like for me to, though I am unsure on exactly how to do so. The issue that I had when trying to push a copy of this to my own account was something having to do with a shallow clone issue. To solve this issue I did the following:
```sh
git rebase -i --root
# Change the first commit to edit in the editor screen that popped up
git commit --amend --no-edit
git rebase --continue
```

This seemed to solve the issue; however, there would only be 3 commits available to browse through which I not what I want, and I see on your mirror that you have all of the commits available. How do I fix this issue and how would you like for me to submit the missing repositories?

Edit: Also, I don't know how important this would be to copy over, but I also have the `zdharma/null` repository as well
